project-todo/routes/web.php
<?php
use App\Enums\Packages;

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Cms\Users\Create\CreateController;
use App\Http\Controllers\Cms\Users\Login\LoginController;
use App\Http\Controllers\Cms\Users\Logout\LogoutController;


use App\Http\Controllers\Cms\Tasks\List\TasksListController;

use App\Http\Controllers\Cms\Home\HomeController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    // return view('welcome');
    return redirect('cms');
});

Route::get('/cms/login',[LoginController::class, 'index'])->name('cms.login');
Route::post('/cms/login',[LoginController::class, 'login'])->name('cms.login.post');

Route::get('/cms/create',[CreateController::class, 'index'])->name('cms.create');
Route::post('/cms/create',[CreateController::class, 'create'])->name('cms.create.post');

Route::get('/cms', function () {
})->middleware(['guest:cms', 'auth.packages']);

Route::prefix('cms')->middleware(['guest:cms'])->name('cms.')->group(function ($route) {

    Route::get('{package}', [HomeController::class, 'index'])->name('home');
    Route::get('{package}/list', [TasksListController::class, 'index'])->name('list');
    
    Route::any('{package}/logout', [LogoutController::class, 'index'])->name('logout');
//     // Route::get('', function () {
//     //     return 123;
//     // })->name('home');
//     // Route::middleware([])->group(function () {
//     //     // dd(request()->all());
        
//     // });

});

// Route::prefix('cms')->middleware('auth.packages')->name('cms.')->group(function () {
    
// });

project-todo/app/Http/Controllers/Cms/Livewire/Partials/Loading.php
<?php

namespace App\Http\Controllers\Cms\Livewire\Partials;

use Livewire\Component;

class Loading extends Component
{
    public function render()
    {
        return view('cms.livewire.partials.loading');
    }
}

project-todo/app/Http/Controllers/Cms/Livewire/Partials/NavigationTop.php
<?php

namespace App\Http\Controllers\Cms\Livewire\Partials;

use Livewire\Component;
use App\Models\Subsription;
use Auth;
use Carbon\Carbon;

class NavigationTop extends Component
{
    public $package;

    public function mount()
    {
    }

    public function cancelPackage()
    {
        $package = Auth::guard('cms')->user()->package_name;
        if ($package == 'free')
        {
            return $this->dispatch('justAlert', type: 'error', message: 'Package của bạn là Free!');
        }

        $subsription = Auth::guard('cms')->user();

        if ($subsription->package_end_date > Carbon::now()) {
            $subsription->package_status = 1;
        } else {
            $subsription->package_name = 'free';
            $subsription->package_end_date = Carbon::now();
            $subsription->package_status = 0;
        }

        $subsription->save();

        return $this->dispatch('justAlert', type: 'success', message: 'Hủy thành công!');
    }

    public function render()
    {
        return view('cms.livewire.partials.navigation-top');
    }
}

project-todo/app/Http/Controllers/Cms/Livewire/Partials/SlideBar.php
<?php

namespace App\Http\Controllers\Cms\Livewire\Partials;

use Livewire\Component;
use Livewire\Attributes\On;
use URL;
use App\Models\PackagesModel;
use App\Models\Subsription;
use Auth;
use Carbon\Carbon;

class SlideBar extends Component
{
    public $packageList = [];
    public $package;

    public function mount()
    {
        $this->package = $package = Auth::guard('cms')->user()->package_name;
        $this->packageList = PackagesModel::where('package_name', '<>', $package)->get();
    }

    #[On('buyPackage')]
    public function buyPackage($package_name)
    {
        $package = $this->packageList->where('package_name', $package_name)->first();
        if (!$package) {
            return $this->dispatch('justAlert', type: 'error', message: 'Package không tồn tại');
        }

        $subsription = Auth::guard('cms')->user();

        $subsription->package_name = $package_name;
        $subsription->package_status = 0;
        $subsription->package_start_date = Carbon::now();
        $subsription->package_end_date = Carbon::now()->addDays($package->duration);

        $subsription->save();

        $this->dispatch('justAlert', type: 'success', message: 'Thành công!');

        return redirect()->route('cms.home', ['package' => $package->package_name]);
    }

    public function render()
    {
        return view('cms.livewire.partials.slide-bar', [
            'current_url' => URL::current(),
        ]);
    }
}

project-todo/app/Http/Controllers/Cms/Livewire/Tasks/List/CreateComponent.php
<?php

namespace App\Http\Controllers\Cms\Livewire\Tasks\List;

use Livewire\Component;
use Livewire\Attributes\Validate;
use App\Models\TasksModel;
use Auth;
use App\Models\PackagesModel;

class CreateComponent extends Component
{
    #[Validate('required|min:10')] 
    public $task_name;

    #[Validate('required|min:20')] 
    public $description;

    public function create()
    {
        $this->validate();

        $package = PackagesModel::where('package_name', Auth::guard('cms')->user()->package_name)->first();

        if ($package->limit_todo != -1) {
            $taskValidate = TasksModel::where('user_id', Auth::guard('cms')->user()->user_id)->limit($package->limit_todo + 1)->count();
            if ($taskValidate >= $package->limit_todo) {
                return $this->dispatch('justAlert', type: 'error', message: 'Tasks của bạn đã vượt hạn mức của gói cho phép!');
            }
        }
        
        TasksModel::create([
            'user_id' => Auth::guard('cms')->user()->user_id,
            'task_name' => $this->task_name,
            'description' => $this->description,
            'status' => 1,
            'left_value' => 1,
            'right_value' => 2,
            'level' => 1,
            'created_by' => Auth::guard('cms')->user()->user_id,
        ]);

        $this->dispatch('justAlert', type: 'success', message: 'Thành công!');
        $this->dispatch('closeModal', 'TasksCreate');
        $this->dispatch('refreshListComponent');

        $this->clearForm();
    }

    public function clearForm()
    {
        $this->task_name = null;
        $this->description = null;
    }

    public function render()
    {
        return view('cms.livewire.tasks.list.create-component');
    }
}

project-todo/app/Http/Controllers/Cms/Livewire/Tasks/List/EditComponent.php
<?php

namespace App\Http\Controllers\Cms\Livewire\Tasks\List;

use Livewire\Component;
use Livewire\Attributes\On;
use Livewire\Attributes\Validate;
use App\Models\TasksModel;

class EditComponent extends Component
{
    public $tasks_id;

    #[Validate('required|min:10')] 
    public $task_name;

    #[Validate('required|min:20')] 
    public $description;

    #[Validate('required|in:0,1,2')] 
    public $status;

    #[On('postTasksEditLoadForm')]
    public function loadFrom($tasks_id)
    {
        $task = TasksModel::where('task_id', $tasks_id)->first();
        $this->tasks_id = $tasks_id;
        $this->task_name = $task->task_name;
        $this->status = $task->status;
        $this->description = $task->description;
    }

    public function edit()
    {
        $this->validate();

        $task = TasksModel::where('task_id', $this->tasks_id)->first();

        $task->task_name = $this->task_name;
        $task->description = $this->description;
        $task->status = $this->status;
        $task->save();

        $this->dispatch('justAlert', type: 'success', message: 'Thành công!');
        $this->dispatch('closeModal', 'TasksEdit');
        $this->dispatch('refreshListComponent');
    }

    public function render()
    {
        return view('cms.livewire.tasks.list.edit-component');
    }
}

project-todo/app/Http/Controllers/Cms/Livewire/Tasks/List/FilterComponent.php
<?php

namespace App\Http\Controllers\Cms\Livewire\Tasks\List;

use Livewire\Component;
use StdClass;
use Carbon\Carbon;

class FilterComponent extends Component
{
    public $dateRange;
    
    public function mount()
    {
        $now = Carbon::now();
        $end = (clone $now)->format('Y-m-d');
        $start = (clone $now)->startOfDay()->format('Y-m-d');
        $this->dateRange = "$start - $end";
    }

    public function previewData() {

        // if (!$this->accountList) {
        //     $this->accountList = [
        //         21862
        //     ];
        // }
        
        $filterParams               = new StdClass();
        $filterParams->dateRange    = $this->dateRange;
        // $filterParams->accountList  = $this->accountList;
        // $filterParams->brandName    = $this->brandName;
        // $filterParams->packageList  = $this->packageList;
        // $filterParams->phoneSearch  = $this->phoneSearch;
        // $filterParams->showPhone    = $this->showPhone;
        // $filterParams->showFullData = $this->showFullData;
        // $filterParams->cmcSearch    = $this->cmcSearch;
        // $filterParams->cmcSubSearch = $this->cmcSubSearch;
        // $filterParams->codeSearch   = $this->codeSearch;
        // $filterParams->code2Search  = $this->code2Search;
        // $filterParams->limit        = self::LIMITDATAPREVIEW;
        // $filterParams->to           = Auth::guard('cms')->user()->email;

        $this->dispatch('postTasksReportList', $filterParams);
    }

    public function render()
    {
        return view('cms.livewire.tasks.list.filter-component');
    }
}

project-todo/app/Http/Controllers/Cms/Livewire/Tasks/List/ListComponent.php
<?php

namespace App\Http\Controllers\Cms\Livewire\Tasks\List;

use Livewire\Component;
use Livewire\Attributes\On;
use Livewire\WithPagination;
use App\Models\TasksModel;
use Carbon\Carbon;
use DB;

class ListComponent extends Component
{
    use WithPagination;

    protected $listeners = [
        'refreshListComponent' => '$refresh'
    ];

    public $filterParams;

    #[On('postTasksReportList')]
    public function updateTasksReportList($filterParams)
    {
        // ...
        $this->filterParams = $filterParams;
        $this->resetPage();
    }

    public function create()
    {
        $this->dispatch('openModalCreate');
    }

    public function edit($id)
    {
        $this->dispatch('postTasksEditLoadForm', $id);
        $this->dispatch('openModalEdit');
    }

    public static function getQuery($filterParams) {
        $tasks = null;
        $filterParams = (array) $filterParams;
        //Check phải có khoảng thời gian
        if ( $filterParams != null && $filterParams['dateRange'] ) {
            $period = $filterParams['dateRange'];

            if ($period) {
                $periodRange = explode(' - ', $period);
                $startDate = Carbon::parse($periodRange[0]);
                $endDate =  Carbon::parse($periodRange[1]);
                if ($startDate && $endDate) {
                    $tasks = TasksModel::select(
                        "task_id",
                        "user_id",
                        "task_name",
                        "description",
                        DB::raw("CASE
                            WHEN `status` = '0' THEN 'Completed'
                            WHEN `status` = '1' THEN 'Doing'
                            WHEN `status` = '2' THEN 'Fail'
                            END AS `status`"
                        ),
                        "created_by",
                        "created_at",
                    )
                    ->whereBetween('created_at', [$startDate->format('Y-m-d 00:00:00'), $endDate->format('Y-m-d 23:59:59')])
                    ->where('status', '<>', -1);
                }
            }
        }

        return $tasks;
    }

    public function render()
    {
        $filterParams = $this->filterParams;
        $query = self::getQuery($filterParams);

        if (!$query) $tasks = [];
        else {
            $tasks = $query->orderBy('created_at', 'desc')->paginate(20);
        }

        return view('cms.livewire.tasks.list.list-component', [
            'tasks' => $tasks
        ]);
    }
}

project-todo/resources/views/cms/livewire/partials/loading.blade.php
<div>
    {{-- The best athlete wants his opponent at his best. --}}
    <div class="scene-box !hidden">
        <div class="scene">
            <div class="cube-wrapper">
            <div class="cube">
                <div class="cube-faces">
                    <div class="cube-face shadow"></div>
                    <div class="cube-face bottom"></div>
                    <div class="cube-face top"></div>
                    <div class="cube-face left"></div>
                    <div class="cube-face right"></div>
                    <div class="cube-face back"></div>
                    <div class="cube-face front"></div>
                </div>
            </div>
            </div>
        </div>
    </div>
</div>

project-todo/resources/views/cms/livewire/partials/navigation-top.blade.php
<div>
    {{-- Stop trying to control. --}}
    <nav class="fixed z-30 w-full bg-gray-50">
        <div class="py-3 px-3 lg:px-5 lg:pl-3">
            <div class="flex justify-between items-center">
                <div class="flex justify-start items-center">
                    <button id="toggleSidebar" aria-expanded="true" aria-controls="sidebar" class="hidden p-2 mr-4 text-gray-600 rounded cursor-pointer lg:inline hover:text-gray-900 hover:bg-gray-100">
                        {{-- <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h6a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path>
                        </svg> --}}
                        <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 448 512">
                            <path d="M0 96C0 78.3 14.3 64 32 64H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32C14.3 128 0 113.7 0 96zM0 256c0-17.7 14.3-32 32-32H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32c-17.7 0-32-14.3-32-32zM448 416c0 17.7-14.3 32-32 32H32c-17.7 0-32-14.3-32-32s14.3-32 32-32H416c17.7 0 32 14.3 32 32z"/>
                        </svg>
                    </button>
                    <button id="toggleSidebarMobile" aria-expanded="true" aria-controls="sidebar" class="p-2 mr-2 text-gray-600 rounded cursor-pointer lg:hidden hover:text-gray-900 hover:bg-gray-100 focus:bg-gray-100 focus:ring-2 focus:ring-gray-100">
                        <svg id="toggleSidebarMobileHamburger" class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h6a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path>
                        </svg>
                        <svg id="toggleSidebarMobileClose" class="hidden w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                        </svg>
                    </button>
                    <p class="text-md font-semibold items-center" id="loading-logo">
                        {{-- <img data-te-lazy-load-init
                            data-te-lazy-src="{{ Vite::asset('resources/cms/images/icons/logo.svg') }}"
                            data-te-lazy-placeholder="{{ Vite::asset('resources/cms/images/icons/loading.gif') }}"
                            class="h-8 object-contain" alt="Creative Tim Logo"> --}}
                        {{-- <span class="country-indicator tw-relative text-xs tw-text-gray-500 tw-leading-3 float-right">Việt Nam</span> --}}
                    </p>
                </div>
                <div class="flex items-center">
                    <div class="ml-3 relative">
                        <div>
                            <button type="button" class="flex items-center text-sm rounded-full focus:ring-4 focus:ring-gray-300" id="user-menu-button-2" aria-expanded="false" data-dropdown-toggle="dropdown-2">
                                <svg class="w-8 h-8 text-gray-500" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-6-3a2 2 0 11-4 0 2 2 0 014 0zm-2 4a5 5 0 00-4.546 2.916A5.986 5.986 0 0010 16a5.986 5.986 0 004.546-2.084A5 5 0 0010 11z" clip-rule="evenodd"></path>
                                </svg>
                                <span class="text-green-600 ml-1">{{ Auth::guard('cms')->user()->username }} ({{ Auth::guard('cms')->user()->user_id }})</span>
                            </button>
                            
                        </div>
                        <div class="hidden w-max z-50 my-4 text-base list-none bg-white rounded divide-y divide-gray-100 shadow-lg shadow-gray-300 right-0 absolute" id="dropdown-2" data-popper-placement="bottom">
                            {{-- <div class="py-3 px-4" role="none">
                                <p class="text-sm" role="none">Neil Sims</p>
                                <p class="text-sm font-medium text-gray-900 truncate" role="none"> neil.sims@flowbite.com </p>
                            </div> --}}
                            <ul class="py-1" role="none">
                                <li>
                                    <a wire:click="cancelPackage" class="block flex py-2 px-4 text-sm text-gray-700 hover:bg-gray-100" role="menuitem">
                                        <div class="w-5 h-5 text-gray-500">{!! XMARK_ICON !!}</div>
                                        <span class="ml-1">Cancel Package</span>
                                    </a>
                                </li>
                                <li class="border-t border-t-gray-200">
                                    <a href="{{ route('cms.logout', ['package' => Auth::guard('cms')->user()->package_name]) }}" class="block flex py-2 px-4 text-sm text-gray-700 hover:bg-gray-100" role="menuitem">
                                        <svg class="w-5 h-5 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1"></path>
                                        </svg>
                                        <span class="ml-1">{{ __('Logout') }}</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</div>
@push('cms.js')
@vite(['resources/assets/cms/js/partials/navigationTop.js'])
@endpush